# Site settings
title: My Stories
description: A collection of original short stories
permalink: /:title/
paginate: 5
darkmode: true

# Build settings
remote_theme: chesterhow/tale
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Author settings
author:
  name: Usman A.
  email: your-email@email.com
  url: https://uabbasi.github.io

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - tools