# Site basics
theme: jekyll-theme-chirpy
lang: en
timezone: America/New_York  # Change to your timezone

# Site info
title: My Stories
tagline: Short Fiction Collection
description: A collection of original short stories
url: "https://uabbasi.github.io"

# Your info
github:
  username: uabbasi

social:
  name: Usman A.
  links:
    - https://www.linkedin.com/in/uabbasi

# Display settings
theme_mode: dark
avatar: /assets/img/avatar.jpg  # Add an image file here
toc: true

# Basic settings
paginate: 10
baseurl: ""
